routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});


Route::get('locale/{locale}', function ($locale) {
    Session::put('locale', $locale);
    return redirect()->back();
});

Route::get('assesment-input', ['uses' => 'Performance\AssessmentController@input','as' => 'assesment.input']);

Route::get('performance/get_assessment/{type?}/{year?}', ['uses' => 'ApiPerformanceController@get_assessment','as' => 'performance.get']);


Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware'=>['auth']], function () {
    Route::get('dashboard/{id?}', ['uses' => 'Admin\DashboardController@index', 'as' => 'dashboard'] );
   
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
   
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
   
    Route::resource('users', 'Admin\UsersController')->except(['show']);
    Route::post('users_delete', ['uses' => 'Admin\UsersController@delete', 'as' => 'users.delete']);
    Route::get('users_datatables', ['uses' => 'Admin\UsersController@datatables', 'as' => 'users.datatables'] );
    
    Route::resource('announcement', 'Admin\AnnouncementController');
    Route::post('announcement_delete', ['uses' => 'Admin\AnnouncementController@delete', 'as' => 'announcement.delete']);
    Route::get('announcement_datatables', ['uses' => 'Admin\AnnouncementController@datatables', 'as' => 'announcement.datatables'] );
});

Route::group(['prefix' => 'setting', 'as' => 'setting.', 'middleware'=>['auth']], function () {
    Route::resource('objective_category', 'Setting\ObjectiveCategoryController');
    Route::post('objective_category_delete', ['uses' => 'Setting\ObjectiveCategoryController@delete', 'as' => 'objective_category.delete']);
    Route::get('objective_category_datatables', ['uses' => 'Setting\ObjectiveCategoryController@datatables', 'as' => 'objective_category.datatables'] );
   
    Route::resource('measure', 'Setting\MeasureController');
    Route::post('measure_delete', ['uses' => 'Setting\MeasureController@delete', 'as' => 'measure.delete']);
    Route::get('measure_datatables', ['uses' => 'Setting\MeasureController@datatables', 'as' => 'measure.datatables'] );

    Route::resource('competency', 'Setting\CompetencyController');
    Route::post('competency_delete', ['uses' => 'Setting\CompetencyController@delete', 'as' => 'competency.delete']);
    Route::get('competency_datatables', ['uses' => 'Setting\CompetencyController@datatables', 'as' => 'competency.datatables'] );
   
    Route::resource('group_rater', 'Setting\GroupRaterController');
    Route::post('group_rater_delete', ['uses' => 'Setting\GroupRaterController@delete', 'as' => 'group_rater.delete']);
    Route::get('group_rater_datatables', ['uses' => 'Setting\GroupRaterController@datatables', 'as' => 'group_rater.datatables'] );

    Route::get('rater', ['uses' => 'Setting\RaterController@index', 'as' => 'rater.index'] );
    Route::get('rater_datatables', ['uses' => 'Setting\RaterController@datatables', 'as' => 'rater.datatables'] );
    Route::get('rater/{id}', ['uses' => 'Setting\RaterController@config', 'as' => 'rater.config'] );
    Route::post('rater_store', ['uses' => 'Setting\RaterController@store', 'as' => 'rater.store']);
    Route::post('rater_destroy', ['uses' => 'Setting\RaterController@destroy', 'as' => 'rater.destroy']);
    Route::get('rater_search', ['uses' => 'Setting\RaterController@search', 'as' => 'rater.search'] );
    
    Route::get('rater_import', ['uses' => 'Setting\RaterController@import', 'as' => 'rater.import'] );
    Route::post('rater_import_store', ['uses' => 'Setting\RaterController@importStore', 'as' => 'rater.importstore']);

    Route::get('general', ['uses' => 'Setting\GeneralController@index', 'as' => 'general.index'] );
    Route::post('general', ['uses' => 'Setting\GeneralController@store', 'as' => 'general.store'] );

    
});

Route::group(['prefix' => 'performance', 'as' => 'performance.', 'middleware'=>['auth']], function () {
   
    Route::get('datatables/{id?}', ['uses' => 'Performance\PerformanceController@datatables', 'as' => 'datatables'] );
    Route::get('data/{id?}', ['uses' => 'Performance\PerformanceController@index','as' => 'data']);
    Route::get('search', ['uses' => 'Performance\PerformanceController@search','as' => 'search']);
    Route::get('export', ['uses' => 'Performance\PerformanceController@export','as' => 'export']);
    Route::get('detail/{id}', ['uses' => 'Performance\PerformanceController@detail','as' => 'detail']);
    Route::get('print/{id}/{score}', ['uses' => 'Performance\PerformanceController@print','as' => 'print']);
    Route::get('show/{type}/{id}', ['uses' => 'Performance\PerformanceController@show','as' => 'show']);
    Route::get('print_kpi/{id}/{type}', ['uses' => 'Performance\MyPerformanceController@printKPI', 'as' => 'print.kpi'] );
    Route::post('destroy', ['uses' => 'Performance\PerformanceController@destroy', 'as' => 'destroy']);
    Route::get('upload', ['uses' => 'Performance\PerformanceController@upload', 'as' => 'upload'] );
    Route::post('upload_store', ['uses' => 'Performance\PerformanceController@uploadStore', 'as' => 'upload.store']);
    Route::get('preview/{id}/{model?}', ['uses' => 'Performance\PerformanceController@preview', 'as' => 'preview'] );
    Route::post('preview_store', ['uses' => 'Performance\PerformanceController@previewStore', 'as' => 'preview.store']);
    Route::post('delete', ['uses' => 'Performance\PerformanceController@delete', 'as' => 'delete']);


    Route::get('history', ['uses' => 'Performance\PerformanceController@history','as' => 'history']);
    Route::get('history_datatables', ['uses' => 'Performance\PerformanceController@historyDatatables', 'as' => 'history.datatables'] );
    Route::get('monitoring/{year?}', ['uses' => 'Performance\PerformanceController@monitoring','as' => 'monitoring']);
    Route::get('monitoring_search', ['uses' => 'Performance\PerformanceController@monitoring_search','as' => 'monitoring.search']);

    Route::get('monitoring_kpi/{year?}/{company?}/{workarea?}/{department?}', ['uses' => 'Performance\PerformanceController@monitoringKPI','as' => 'monitoring.kpi']);
    Route::get('monitoring_kpi_datatables/{year?}/{company?}/{workarea?}/{department?}', ['uses' => 'Performance\PerformanceController@monitoringKPI_datatables','as' => 'monitoring.kpi.datatables']);
    Route::get('monitoring_kpi_search', ['uses' => 'Performance\PerformanceController@monitoringKPI_search','as' => 'monitoring.kpi.search']);

    Route::get('adjust/{id}', ['uses' => 'Performance\PerformanceController@adjust','as' => 'adjust']);
    Route::post('adjust_store', ['uses' => 'Performance\PerformanceController@adjustStore','as' => 'adjust.store']);
    Route::get('adjust_upload', ['uses' => 'Performance\PerformanceController@adjust_upload','as' => 'adjust.upload']);
    Route::post('adjust_upload_store', ['uses' => 'Performance\PerformanceController@adjust_upload_store','as' => 'adjust.upload.store']);


});

Route::group(['middleware'=>['auth']], function () {
    Route::match(['get', 'post'], 'profile/change_profile', ['uses' => 'Admin\ProfileController@changeProfile', 'as' => 'profile.change_profile']);
    Route::match(['get', 'post'], 'profile/change_password', ['uses' => 'Admin\ProfileController@changePassword', 'as' => 'profile.change_password']);
    
    Route::get('announcement_read', ['uses' => 'Admin\AnnouncementController@read', 'as' => 'announcement.read'] );
    Route::post('announcement_read', ['uses' => 'Admin\AnnouncementController@search', 'as' => 'announcement.search'] );
   
    Route::get('notifications', ['uses' => 'Admin\NotificationController@index', 'as' => 'notifications'] );
    Route::get('notifications/{id}', ['uses' => 'Admin\NotificationController@show', 'as' => 'notifications.show'] );
   
    Route::get('get_employee', ['uses' => 'Setting\MasterController@getEmployee'] );
    Route::get('get_department/{id}', ['uses' => 'Setting\MasterController@getDepartment'] );
    Route::get('get_workarea/{id}', ['uses' => 'Setting\MasterController@getWorkarea'] );

});

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Auth::routes();



// EMPLOYEEE
Route::post('signin', ['uses' => 'SigninController@attempt','as' => 'signin']);
Route::post('sign', ['uses' => 'SigninController@login','as' => 'sign']);
Route::get('personal_detail_public/{id}/{year}/', ['uses' => 'Performance\MyPerformanceController@publicView', 'as' => 'personal.public.view'] );
Route::get('personal_detail_print/{id}/{year}/{type}', ['uses' => 'Performance\MyPerformanceController@publicPrint', 'as' => 'personal.public.print'] );

Route::group(['middleware'=>['checksigned']], function () {
    Route::get('announcement_read', ['uses' => 'Dashboard\AnnouncementController@read', 'as' => 'announcement.read'] );
});

Route::group(['prefix' => 'myperformance', 'as' => 'myperformance.', 'middleware'=>['checksigned']], function () {
    
    Route::get('detail/{type}/{id}', ['uses' => 'Performance\MyPerformanceController@detail','as' => 'detail']);
    Route::get('print/{id}/{score}', ['uses' => 'Performance\MyPerformanceController@print', 'as' => 'print'] );
    Route::get('show/{id}', ['uses' => 'Performance\MyPerformanceController@show','as' => 'show']);

app/Http/Controllers/Setting/CompetencyController.php
<?php

namespace App\Http\Controllers\Setting;

use App\Models\Competency;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Vinkla\Hashids\Facades\Hashids;
use Yajra\DataTables\Facades\DataTables;
use Carbon\Carbon;
use Auth;

class CompetencyController extends Controller
{
    /**
     * Display a listing of Group.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('setting')) {
            return abort(401);
        }
        return view('setting.competency.index');
    }

    public function datatables()
    {
        if (! Gate::allows('setting')) {
            return abort(401);
        }
        $result = DB::table('competencies');

       return  DataTables::of($result)
        ->addColumn('action', function ($result) {
            $url_edit = "<a href='".route('setting.competency.edit', Hashids::encode($result->id))."' title='".trans('app.edit_title')."' data-toggle='tooltip' class='btn btn-outline'><span class='ti-pencil icon-lg'></span> </a>";  
            $url_delete = "<form class='delete' action='".route('setting.competency.delete', ['id' => $result->id])."' method='POST'>
                            ".csrf_field()."
                            <button class='btn btn-outline text-danger' title='".trans('app.delete_title')."' data-toggle='tooltip'><i class='ti-trash icon-lg'></i></button>
                          </form>";
            return
                '<div class="btn-group">'
                 .$url_edit .$url_delete.
                '</div>';
        }) 
        ->editColumn('status', function ($result) {
            return getStatusData($result->status);
        })
        ->editColumn('updated_at', function ($result) {
            return $result->updated_at ? with(new Carbon($result->updated_at))->format('m/d/Y') : '';
        })
        ->rawColumns(['action', 'status'])
        ->make(true);

    }

    /**
     * Show the form for creating new Group.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('setting')) {
            return abort(401);
        }

        return view('setting.competency.create');
    }

    /**
     * Store a newly created Group in storage.
     *
     * @param  \App\Http\Requests\StoreGroupsRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (! Gate::allows('setting')) {
            return abort(401);
        }

        $data = $request->all();
        $data['created_by'] = Auth::user()->id;

        $competency = Competency::create($data);

        return redirect()->route('setting.competency.index')->with(['success' => 'Add was successful!']);
    }


    /**
     * Show the form for editing Group.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('setting')) {
            return abort(401);
        }
        $id = Hashids::decode($id);
        $competency = Competency::findOrFail($id['0']);

        return view('setting.competency.edit', compact('competency'));
    }

    /**
     * Update Group in storage.
     *
     * @param  \App\Http\Requests\  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (! Gate::allows('setting')) {
            return abort(401);
        }
        $data = $request->all();
        if($request->get('status')){
            $data['status'] = 1;
        }else{
            $data['status'] = 0;
        }
        $data['updated_by'] = Auth::user()->id;

        $competency = Competency::findOrFail($id);
        $competency->update($data);

        return redirect()->route('setting.competency.index')->with(['success' => 'Edit was successful!']);
        
    }

    /**
     * Remove Group from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {

        print_r($request->id).exit();
        if (! Gate::allows('setting')) {
            return abort(401);
        }

        $competency  = Competency::findOrFail($id);
        $competency->delete();
      
        return redirect()->route('setting.competency.index')->with(['success' => 'Delete was successful!']);

    }

    public function delete(Request $request)
    {

        if (! Gate::allows('setting')) {
            return abort(401);
        }

        $competency  = Competency::findOrFail($request->id);
        $competency->delete();
      
        return redirect()->route('setting.competency.index')->with(['success' => 'Delete was successful!']);

    }

    public function getItem()
    {
        return Competency::get()->pluck('name', 'id');
    }

}

app/Http/Controllers/Setting/GeneralController.php
<?php

namespace App\Http\Controllers\Setting;

use App\Models\Setting;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Vinkla\Hashids\Facades\Hashids;
use Yajra\DataTables\Facades\DataTables;
use Carbon\Carbon;
use Auth;

class GeneralController extends Controller
{
    /**
     * Display a listing of Group.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('setting')) {
            return abort(401);
        }
        return view('setting.general.index');
    }


    /**
     * Update Group in storage.
     *
     * @param  \App\Http\Requests\  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (! Gate::allows('setting')) {
            return abort(401);
        }
        
        $delete = Setting::truncate();

        $setting    = [];
        $key        = $request->get('key');

        for($i=0;$i < count($key);$i++) {
            $setting[] = [
                'key'    => $request->get('key')[$i],
                'value'  => $request->get('val')[$i],
            ];
        }

        $setting = Setting::insert($setting);


        return redirect()->route('setting.general.index')->with(['success' => 'Edit was successful!']);
        
    }


}

app/Http/Controllers/Setting/MasterController.php
<?php

namespace App\Http\Controllers\Setting;

use Illuminate\Http\Request;
use App\Models\Division;
use App\Models\Department;
use App\Models\Employee;
use App\Models\Workarea;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;

class MasterController extends Controller
{
   
    
    public function getEmployee(Request $request)
    {
        if ($request->has('q')) {
            $data = 
            DB::table('db_klola_hes.sys_ttrs_employee AS employee')
            ->select('employee.*', 'department.name AS department','unit.name AS workarea')
            ->where('employee.firstname', 'like', '%' .$request->q . '%')
            ->orWhere('employee.nip', 'like', '%' .$request->q . '%')
            ->leftjoin('db_klola_hes.sys_tmst_department AS department', 'department.id', '=', 'employee.sys_tmst_department_id')
            ->leftjoin('db_klola_hes.sys_tmst_unit AS unit', 'unit.id', '=', 'employee.sys_tmst_unit_id')
            ->get();
            $result = array();    
            foreach ($data as $val) {
                $result[] = array('id' => $val->id,  'nik' => $val->nip, 'name' => $val->firstname, 'department' => $val->department,'workarea' => $val->workarea);
            }
            return response()->json($result);
        }
    }

    public function getDepartment($company)
    {
        return Department::pluck('name', 'id');
    }

    public function getWorkarea($company)
    {
        return Workarea::pluck('name', 'id');
    }


}

resources/views/setting/raters/config.blade.php
@extends('layouts.app')

@section('page-header')
    @lang('app.setting')
@endsection

@section('breadcrumbs')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">@lang('app.home')</a></li>
        <li class="breadcrumb-item"><a href="#">@lang('app.setting')</a></li>
		<li class="breadcrumb-item"><a href="{{ route('setting.rater.index') }}">@lang('pm.raters')</a></li>
        <li class="breadcrumb-item active" aria-current="page">@lang('pm.form_setting_raters')</li>
    </ol>
@endsection

@section('content')

	<div class="row">
		<div class="col-lg-12">
		
			<div class="card">
				<div class="card-body p-30">
				<h6>@lang ('pm.form_setting_raters') </h6>
					<hr class="mB-30">    
					<div class="form-group row">
						<label class="col-sm-2 text-right">@lang('pm.emp_name')</label>
						<div class="col-sm-6">
						: {{ $employee->firstname }}
						</div>
					</div>
					<div class="form-group row">
						<label class="col-sm-2 text-right">@lang('pm.emp_id')</label>
						<div class="col-sm-6">
						: {{ $employee->nip }}
						</div>
					</div>
					<div class="form-group row">
						<label class="col-sm-2 text-right">{{ __('pm.position') }} </label>
						<div class="col-sm-6">
							: {{ $employee->jabatan }}
						</div>
					</div>
					<div class="form-group row">
						<label class="col-sm-2 text-right">{{ __('pm.division') }} /  {{ __('pm.department') }}</label>
						<div class="col-sm-6">
							: {{ $employee->department}}
						</div>
					</div>
					<div class="form-group row">
						<label class="col-sm-2 text-right">{{ __('pm.workarea') }} </label>
						<div class="col-sm-6">
							: {{ $employee->workarea}}
						</div>
					</div>	
			
					<div class="alert alert-info m-t-30">
						@lang('pm.setting_raters_info')
					</div>

					
					<form action="{{ route('setting.rater.store') }}" method="POST">
                    {{ csrf_field() }}
						<input type="hidden" value="{{ $rater->employee_id }}" name="employee_id">

						<table class="table table-bordered">
							<thead>
								<tr>
									<th style="width:200px"> {{ __('app.group_raters') }}</th>
									<th> {{ __('pm.raters') }}</th>
								</tr>
							</thead>

							<?php 
								$rater = json_decode($rater->rate,true);
							?>

							@foreach ($rater as $val)
								<?php 
									$employee='';
									if($val['value'] != null){
										$getEmployee = getDataByParam('db_klola_hes.sys_ttrs_employee','nip',$val['value']);
										if($getEmployee){
											$employee = strtoupper($getEmployee->firstname);
										}else{
											$employee='';
										}
									}
								?>
								<tr>
									<td>
										{{ $val['key'] }}
										<input type="hidden" value="{{$val['key']}}" name="group[]">
									</td>
									<td>
										<select class="form-control employee" name="rater_id[]">
											<option value="{{$val['value']}}" selected>{{$val['value']}} - {{ $employee }}</option>
										</select>
									</td>
								</tr>
							@endforeach

						</table>
						<hr>						
						<div class="float-right">
							<div class="col-sm-12">
								<a href="{{ route('setting.group_rater.index') }}" class="btn btn-light">{{ trans('global.app_cancel') }}</a>
								<button type="submit" class="btn bg-gradient-success"><i class="ti-save m-r-10"></i> {{ __('app.submit') }}</button>
							</div>
						</div>

					</form>
					
				</div>
			</div>
				
		</div>
	</div>

@endsection

@section('js')
	<script>
		$(document).ready(function(){

			$('.employee').select2({
                placeholder: 'Cari Employee dengan mengetik 3 huruf...',
				allowClear: true,
				minimumInputLength: 3,
                ajax: {
                    url: '/get_employee/',
                    dataType: 'json',
                    delay: 250,
                    processResults: function (data) {
                        return {
                            results:  $.map(data, function (item) {
                                return {
                                    text: item.nik + " [" + item.name + "/" + item.department + "/" + item.workarea + "]",
                                    id: item.nik
                                }
                            })
                        };
                    },
                    cache: true
                }
            });
			
			$(document).on("click", "#btn-submit", function(e) {
				$('input[name="status"]').val('1');
			});
		
		});
	</script>
@endsection

resources/views/setting/raters/search.blade.php
@extends('layouts.app')

@section('page-header')
    @lang('app.setting')
@endsection

@section('breadcrumbs')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">@lang('app.home')</a></li>
        <li class="breadcrumb-item"><a href="#">@lang('app.setting')</a></li>
        <li class="breadcrumb-item"><a href="{{ route('setting.rater.index') }}">@lang('pm.raters')</a></li>
        <li class="breadcrumb-item active" aria-current="page">@lang('global.app_search')</li>
    </ol>
@endsection

@section('content')

    <div class="row">
    <div class="col-lg-12">
                    
        <div class="card">
            <div class="card-body p-30">
            
                <div class="pad-btm">
                    <div class="table-toolbar-right">
                        <div class="btn-group">
                        <button class="btn btn-default"  data-toggle="collapse" data-target="#filter"><i class="ti-filter"></i> Filter</button>
                        <a href="{{ route('setting.rater.import') }}" class="btn bg-gradient-success"><i class="fa fa-file-excel-o"></i> Import</a>
                        </div>
                    </div>

                    <div class="collapse" id="filter">
                        <hr>
                        <form class="form-inline" action="{{ route('setting.rater.search')}}" method='GET'>
                            {{ csrf_field() }}
                            <div class="form-group mb-2 col-sm-3">
                                <label>{{ trans('pm.company') }}</label>
                                {!! Form::select('company_id', $company, null, ['class' => 'form-control select2']) !!}
                            </div>
                            <div class="form-group mb-2 col-sm-3">
                                <label>{{ trans('pm.workarea') }}</label>
                                {!! Form::select('workarea_id', $workarea, null, ['class' => 'form-control select2']) !!}
                            </div>
                            <div class="form-group mb-2 col-sm-3">
                                <label>{{ trans('pm.department') }}</label>
                                {!! Form::select('department_id', $department, null, ['class' => 'form-control select2']) !!}
                            </div>
                            <div class="form-group mb-2 col-sm-3">
                                <label>{{ trans('pm.level') }}</label>
                                {!! Form::select('level_id', $level, null, ['class' => 'form-control select2']) !!}
                            </div>
                            <div class="form-group m-t-20 col-sm-12">
                                <button type="submit" class="btn bg-gradient-blue float-right">@lang('global.app_search')</button>
                            </div>
                        </form>
                        <hr>
                    </div>

                </div>

                <p>{!! $search !!}</p>
                <div class="table-responsive">
                    <table id="dataTables" class="table table-striped " cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>{{ trans('pm.emp_id') }}</th>
                                <th>{{ trans('pm.emp_name') }}</th>
                                <th>{{ trans('pm.workarea') }}</th>
                                <th>{{ trans('pm.department') }}</th>
                                <th>{{ trans('app.action') }}</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if(count($rater) > 0)
                                @foreach ($rater as $item)
                                    <tr >
                                        <td>{{ $item->nip }}</td>
                                        <td>{{ $item->nama }}</td>
                                        <td>{{ $item->workarea }}</td>
                                        <td>{{ $item->department }}</td>
                                        <td>
                                            <?php
                                                $url_config = "<a href='".route('setting.rater.config',$item->nip)."' title='".trans('global.app_edit')."' data-toggle='tooltip' class='btn btn-outline'><span class='ti-settings icon-lg'></span> </a>";  
                                                echo $url_config;
                                            ?>
                                        </td>
                                    </tr>
                                @endforeach
                            @else
                                <tr><td colspan="5" class="text-center"> @lang('global.app_no_entries_in_table')</td></tr>
                            @endif
                        </tbody>
                    </table>
                    {{ $rater->links() }}
                </div>

            </div>
        </div>
            
    </div>
    </div>

@endsection

@section('js')
    <script>
    $(document).ready(function() {

        var $company = $(".company");
            var $department = $(".department");
            var $workarea = $(".workarea");
           
            $department.select2({
                placeholder:"{{ __('global.app_choose') }}"
            });
            $workarea.select2({
                placeholder:"{{ __('global.app_choose') }}"
            });

            $company.select2({
                placeholder:"{{ __('global.app_choose') }}"
            }).on('change', function() {
                $.ajax({
                    url:"/get_department/" + $company.val(), 
                    type:'GET',
                    success:function(data) {
                        $department.empty();
                        $department.append($("<option></option>").attr("value", "").text("{{ __('global.app_choose') }}")); 
                        $.each(data, function(value, key) {
                            $department.append($("<option></option>").attr("value", value).text(key)); 
                        });
                        $department.select2();
                    }
                });
                $.ajax({
                    url:"/get_workarea/" + $company.val(), 
                    type:'GET',
                    success:function(data) {
                        $workarea.empty();
                        $workarea.append($("<option></option>").attr("value", "").text("{{ __('global.app_choose') }}")); 
                        $.each(data, function(value, key) {
                            $workarea.append($("<option></option>").attr("value", value).text(key));
                        });
                        $workarea.select2();
                    }
                });
            });

    });
</script>
@stop