routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});


Route::get('locale/{locale}', function ($locale) {
    Session::put('locale', $locale);
    return redirect()->back();
});

Route::get('assesment-input', ['uses' => 'Performance\AssessmentController@input','as' => 'assesment.input']);

Route::get('performance/get_assessment/{type?}/{year?}', ['uses' => 'ApiPerformanceController@get_assessment','as' => 'performance.get']);


Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware'=>['auth']], function () {
    Route::get('dashboard/{id?}', ['uses' => 'Admin\DashboardController@index', 'as' => 'dashboard'] );
   
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
   
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
   
    Route::resource('users', 'Admin\UsersController')->except(['show']);
    Route::post('users_delete', ['uses' => 'Admin\UsersController@delete', 'as' => 'users.delete']);
    Route::get('users_datatables', ['uses' => 'Admin\UsersController@datatables', 'as' => 'users.datatables'] );
    
    Route::resource('announcement', 'Admin\AnnouncementController');
    Route::post('announcement_delete', ['uses' => 'Admin\AnnouncementController@delete', 'as' => 'announcement.delete']);
    Route::get('announcement_datatables', ['uses' => 'Admin\AnnouncementController@datatables', 'as' => 'announcement.datatables'] );
});

Route::group(['prefix' => 'setting', 'as' => 'setting.', 'middleware'=>['auth']], function () {
    Route::resource('objective_category', 'Setting\ObjectiveCategoryController');
    Route::post('objective_category_delete', ['uses' => 'Setting\ObjectiveCategoryController@delete', 'as' => 'objective_category.delete']);
    Route::get('objective_category_datatables', ['uses' => 'Setting\ObjectiveCategoryController@datatables', 'as' => 'objective_category.datatables'] );
   
    Route::resource('measure', 'Setting\MeasureController');
    Route::post('measure_delete', ['uses' => 'Setting\MeasureController@delete', 'as' => 'measure.delete']);
    Route::get('measure_datatables', ['uses' => 'Setting\MeasureController@datatables', 'as' => 'measure.datatables'] );

    Route::resource('competency', 'Setting\CompetencyController');
    Route::post('competency_delete', ['uses' => 'Setting\CompetencyController@delete', 'as' => 'competency.delete']);
    Route::get('competency_datatables', ['uses' => 'Setting\CompetencyController@datatables', 'as' => 'competency.datatables'] );
   
    Route::resource('group_rater', 'Setting\GroupRaterController');
    Route::post('group_rater_delete', ['uses' => 'Setting\GroupRaterController@delete', 'as' => 'group_rater.delete']);
    Route::get('group_rater_datatables', ['uses' => 'Setting\GroupRaterController@datatables', 'as' => 'group_rater.datatables'] );

    Route::get('rater', ['uses' => 'Setting\RaterController@index', 'as' => 'rater.index'] );
    Route::get('rater_datatables', ['uses' => 'Setting\RaterController@datatables', 'as' => 'rater.datatables'] );
    Route::get('rater/{id}', ['uses' => 'Setting\RaterController@config', 'as' => 'rater.config'] );
    Route::post('rater_store', ['uses' => 'Setting\RaterController@store', 'as' => 'rater.store']);
    Route::post('rater_destroy', ['uses' => 'Setting\RaterController@destroy', 'as' => 'rater.destroy']);
    Route::get('rater_search', ['uses' => 'Setting\RaterController@search', 'as' => 'rater.search'] );
    
    Route::get('rater_import', ['uses' => 'Setting\RaterController@import', 'as' => 'rater.import'] );
    Route::post('rater_import_store', ['uses' => 'Setting\RaterController@importStore', 'as' => 'rater.importstore']);

    Route::get('general', ['uses' => 'Setting\GeneralController@index', 'as' => 'general.index'] );
    Route::post('general', ['uses' => 'Setting\GeneralController@store', 'as' => 'general.store'] );

    
});

Route::group(['prefix' => 'performance', 'as' => 'performance.', 'middleware'=>['auth']], function () {
   
    Route::get('datatables/{id?}', ['uses' => 'Performance\PerformanceController@datatables', 'as' => 'datatables'] );
    Route::get('data/{id?}', ['uses' => 'Performance\PerformanceController@index','as' => 'data']);
    Route::get('search', ['uses' => 'Performance\PerformanceController@search','as' => 'search']);
    Route::get('export', ['uses' => 'Performance\PerformanceController@export','as' => 'export']);
    Route::get('detail/{id}', ['uses' => 'Performance\PerformanceController@detail','as' => 'detail']);
    Route::get('print/{id}/{score}', ['uses' => 'Performance\PerformanceController@print','as' => 'print']);
    Route::get('show/{type}/{id}', ['uses' => 'Performance\PerformanceController@show','as' => 'show']);
    Route::get('print_kpi/{id}/{type}', ['uses' => 'Performance\MyPerformanceController@printKPI', 'as' => 'print.kpi'] );
    Route::post('destroy', ['uses' => 'Performance\PerformanceController@destroy', 'as' => 'destroy']);
    Route::get('upload', ['uses' => 'Performance\PerformanceController@upload', 'as' => 'upload'] );
    Route::post('upload_store', ['uses' => 'Performance\PerformanceController@uploadStore', 'as' => 'upload.store']);
    Route::get('preview/{id}/{model?}', ['uses' => 'Performance\PerformanceController@preview', 'as' => 'preview'] );
    Route::post('preview_store', ['uses' => 'Performance\PerformanceController@previewStore', 'as' => 'preview.store']);
    Route::post('delete', ['uses' => 'Performance\PerformanceController@delete', 'as' => 'delete']);


    Route::get('history', ['uses' => 'Performance\PerformanceController@history','as' => 'history']);
    Route::get('history_datatables', ['uses' => 'Performance\PerformanceController@historyDatatables', 'as' => 'history.datatables'] );
    Route::get('monitoring/{year?}', ['uses' => 'Performance\PerformanceController@monitoring','as' => 'monitoring']);
    Route::get('monitoring_search', ['uses' => 'Performance\PerformanceController@monitoring_search','as' => 'monitoring.search']);

    Route::get('monitoring_kpi/{year?}/{company?}/{workarea?}/{department?}', ['uses' => 'Performance\PerformanceController@monitoringKPI','as' => 'monitoring.kpi']);
    Route::get('monitoring_kpi_datatables/{year?}/{company?}/{workarea?}/{department?}', ['uses' => 'Performance\PerformanceController@monitoringKPI_datatables','as' => 'monitoring.kpi.datatables']);
    Route::get('monitoring_kpi_search', ['uses' => 'Performance\PerformanceController@monitoringKPI_search','as' => 'monitoring.kpi.search']);

    Route::get('adjust/{id}', ['uses' => 'Performance\PerformanceController@adjust','as' => 'adjust']);
    Route::post('adjust_store', ['uses' => 'Performance\PerformanceController@adjustStore','as' => 'adjust.store']);
    Route::get('adjust_upload', ['uses' => 'Performance\PerformanceController@adjust_upload','as' => 'adjust.upload']);
    Route::post('adjust_upload_store', ['uses' => 'Performance\PerformanceController@adjust_upload_store','as' => 'adjust.upload.store']);


});

Route::group(['middleware'=>['auth']], function () {
    Route::match(['get', 'post'], 'profile/change_profile', ['uses' => 'Admin\ProfileController@changeProfile', 'as' => 'profile.change_profile']);
    Route::match(['get', 'post'], 'profile/change_password', ['uses' => 'Admin\ProfileController@changePassword', 'as' => 'profile.change_password']);
    
    Route::get('announcement_read', ['uses' => 'Admin\AnnouncementController@read', 'as' => 'announcement.read'] );
    Route::post('announcement_read', ['uses' => 'Admin\AnnouncementController@search', 'as' => 'announcement.search'] );
   
    Route::get('notifications', ['uses' => 'Admin\NotificationController@index', 'as' => 'notifications'] );
    Route::get('notifications/{id}', ['uses' => 'Admin\NotificationController@show', 'as' => 'notifications.show'] );
   
    Route::get('get_employee', ['uses' => 'Setting\MasterController@getEmployee'] );
    Route::get('get_department/{id}', ['uses' => 'Setting\MasterController@getDepartment'] );
    Route::get('get_workarea/{id}', ['uses' => 'Setting\MasterController@getWorkarea'] );

});

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Auth::routes();



// EMPLOYEEE
Route::post('signin', ['uses' => 'SigninController@attempt','as' => 'signin']);
Route::post('sign', ['uses' => 'SigninController@login','as' => 'sign']);
Route::get('personal_detail_public/{id}/{year}/', ['uses' => 'Performance\MyPerformanceController@publicView', 'as' => 'personal.public.view'] );
Route::get('personal_detail_print/{id}/{year}/{type}', ['uses' => 'Performance\MyPerformanceController@publicPrint', 'as' => 'personal.public.print'] );

Route::group(['middleware'=>['checksigned']], function () {
    Route::get('announcement_read', ['uses' => 'Dashboard\AnnouncementController@read', 'as' => 'announcement.read'] );
});

Route::group(['prefix' => 'myperformance', 'as' => 'myperformance.', 'middleware'=>['checksigned']], function () {
    
    Route::get('detail/{type}/{id}', ['uses' => 'Performance\MyPerformanceController@detail','as' => 'detail']);
    Route::get('print/{id}/{score}', ['uses' => 'Performance\MyPerformanceController@print', 'as' => 'print'] );
    Route::get('show/{id}', ['uses' => 'Performance\MyPerformanceController@show','as' => 'show']);

app/Models/Announcement.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Announcement extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'announcements';
    /**
     * The primary key associated with the table.
     *
     * @var string
     */
    protected $primaryKey = 'id';
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['content','title', 'status','expired','created_by'];

      /*
    |------------------------------------------------------------------------------------
    | Attributes
    |------------------------------------------------------------------------------------
    */

    
}

app/Http/Controllers/Admin/AnnouncementController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Announcement;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Vinkla\Hashids\Facades\Hashids;
use Yajra\DataTables\Facades\DataTables;
use Carbon\Carbon;
use Auth;

class AnnouncementController extends Controller
{
    /**
     * Display a listing of Items.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('announcement')) {
            return abort(401);
        }
        return view('admin.announcement.index');
    }

    public function datatables()
    {
        if (! Gate::allows('announcement')) {
            return abort(401);
        }
        $result = DB::table('announcements');

       return  DataTables::of($result)
        ->addColumn('action', function ($result) {
            $url_edit = "<a href='".route('admin.announcement.edit', Hashids::encode($result->id))."' title='".trans('app.edit_title')."' data-toggle='tooltip' class='btn btn-outline'><span class='ti-pencil icon-lg'></span> </a>";  
            $url_delete = "<form class='delete' action='".route('admin.announcement.delete', ['id' => $result->id])."' method='POST'>
                                 ".csrf_field()."
                                <button type='submit' class='btn btn-outline text-danger' title='".trans('app.delete_title')."' data-toggle='tooltip'><i class='ti-trash icon-lg'></i></button>
                            </form>";
            return
                '<div class="btn-group">'
                 .$url_edit .$url_delete.
                '</div>';
        })->addColumn('status', function ($result){
            if($result->status==1){
                return "<span class='badge badge-success'>Aktif</span>";
            }else{
                return "<span class='badge badge-danger'>Non Aktif</span>";
            }
        })
        ->editColumn('updated_at', function ($result) {
            return $result->updated_at ? with(new Carbon($result->updated_at))->format('m/d/Y') : '';
        })
        ->rawColumns(['action', 'status'])
        ->make(true);

    }

    /**
     * Show the form for creating new Items.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('announcement')) {
            return abort(401);
        }

        return view('admin.announcement.create');
    }

    /**
     * Store a newly created Items in storage.
     *
     * @param  \App\Http\Requests\StoreItemssRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (! Gate::allows('announcement')) {
            return abort(401);
        }
        $data = $request->all();
        $data['expired']    = dateNumID2MySQL($request->get('expired'));
        $data['created_by'] = Auth::user()->id;

        $items = Announcement::create($data);

        return redirect()->route('admin.announcement.index')->with(['success' => 'Add was successful!']);
    }


    /**
     * Show the form for editing Items.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('announcement')) {
            return abort(401);
        }
        $id     = Hashids::decode($id);
        $announcement = Announcement::findOrFail($id['0']);

        return view('admin.announcement.edit', compact('announcement'));
    }
    

    /**
     * Update Items in storage.
     *
     * @param  \App\Http\Requests\  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (! Gate::allows('announcement')) {
            return abort(401);
        }
        
        $data = $request->all();
        if($request->get('status')){
            $data['status'] = 1;
        }else{
            $data['status'] = 0;
        }
        $data['expired']    = dateNumID2MySQL($request->get('expired'));
        $data['updated_by'] = Auth::user()->id;
        $items = Announcement::findOrFail($id);
        $items->update($data);

        return redirect()->route('admin.announcement.index')->with(['success' => 'Edit was successful!']);
        
    }

    /**
     * Remove Items from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function delete(Request $request)
    {

        if (! Gate::allows('announcement')) {
            return abort(401);
        }
        $items  = Announcement::findOrFail($request->id);
        $items->delete();
        return redirect()->route('admin.announcement.index')->with(['success' => 'Delete was successful!']);

    }

    public function read()
    {
        $announcement = Announcement::where('status',1)->paginate(15);
        return view('admin.announcement.read', compact('announcement'));
    }

    public function search(Request $request){
        $announcement = Announcement::when($request->q, function ($query) use ($request) {
                  $query->where('title', 'ILIKE', "%{$request->q}%")
                        ->orWhere('content', 'ILIKE', "%{$request->q}%");
                  })->paginate(8);
        return view('admin.announcement.read', compact('announcement'));
     }

}

app/Http/Controllers/Dashboard/AnnouncementController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Announcement;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Vinkla\Hashids\Facades\Hashids;
use Yajra\DataTables\Facades\DataTables;
use Carbon\Carbon;
use Auth;

class AnnouncementController extends Controller
{

    public function read()
    {
        $announcement = Announcement::where('status',1)->paginate(15);
        return view('personal.dashboard.announcement', compact('announcement'));
    }

    public function search(Request $request){
        $announcement = Announcement::when($request->q, function ($query) use ($request) {
                  $query->where('title', 'ILIKE', "%{$request->q}%")
                        ->orWhere('content', 'ILIKE', "%{$request->q}%");
                  })->paginate(8);
        return view('personal.dashboard.announcement', compact('announcement'));
     }

}

resources/views/admin/announcement/create.blade.php
@extends('layouts.app')

@section('page-header')
    @lang('app.announcement')
@endsection

@section('breadcrumbs')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">@lang('app.home')</a></li>
        <li class="breadcrumb-item"><a href="{{ route('admin.announcement.index') }}">@lang('app.announcement')</a></li>
        <li class="breadcrumb-item active" aria-current="page">@lang('global.app_create')</li>
    </ol>
@endsection

@section('content')

	<div class="row mB-40">
        <div class="col-sm-12">
            <div class="card p-20 bd">

                {!! Form::open(['method' => 'POST', 'route' => ['admin.announcement.store']]) !!}
                    <div class="form-group row mt-3">
                        <label class="col-sm-2 col-form-label text-right">@lang('app.title') <span class="text-danger">*</span></label>
                        <div class="col-sm-8">
                            {!! Form::text('title', old('title'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                            <p class="help-block"></p>
                            @if($errors->has('title'))
                                <p class="help-block">
                                    {{ $errors->first('title') }}
                                </p>
                            @endif
                        </div>
                    </div>  

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label text-right">@lang('app.content')</label>
                        <div class="col-sm-6">
                            {!! Form::textarea('content', old('content'), ['class' => 'form-control description', 'rows' => 4, 'placeholder' => '']) !!}
                            <p class="help-block"></p>
                            @if($errors->has('content'))
                                <p class="help-block">
                                    {{ $errors->first('content') }}
                                </p>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label text-right">@lang('app.expired')</label>
                        <div class="col-sm-4">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="ti-calendar"></i></span>
                                </div>
                                {!! Form::text('expired', null , ['class' => 'form-control  datepicker', 'placeholder' => '', 'required' => '']) !!}
                            </div>
                            <p class="help-block"></p>
                            @if($errors->has('expired'))
                                <p class="help-block">
                                    {{ $errors->first('expired') }}
                                </p>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row">
                    <label class="col-sm-2 col-form-label text-right">@lang('app.status') <span class="text-danger">*</span></label>
                    <div class="col-sm-6">
                        <input type="checkbox" name="status" class="switch switch-info" id="status" value="0">
                        <p class="help-block"></p>
                        @if($errors->has('status'))
                            <p class="help-block">
                                {{ $errors->first('status') }}
                            </p>
                        @endif
                    </div>
                </div>
                    
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label text-right"></label>
                        <div class="col-sm-8">
                            <a href="{{ route('admin.announcement.index') }}" class="btn btn-light">{{ trans('global.app_cancel') }}</a>
                            {!! Form::submit(trans('global.app_save'), ['class' => 'btn btn-danger']) !!}
                        </div>
                    </div>

                {!! Form::close() !!}       
            </div>  
        </div>
    </div>
        
@endsection



@section('js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/5.0.11/tinymce.min.js"></script>
    <script>
        $(document).ready(function() {
            if($('#status').val()=='1'){
                $('#status').attr('checked','checked').iCheck('update');
            }
            $('#status').on('ifChecked', function(){
                $("#status" ).attr('value', '1');
            });
            $('#status').on('ifUnchecked', function(){
                $("#status" ).attr('value', '0');
            });
            tinymce.init({
                selector:'textarea.description',
                width: 800,
                height: 300
            });
        });
    </script>
@stop

resources/views/admin/announcement/edit.blade.php
@extends('layouts.app')

@section('page-header')
    @lang('app.announcement')
@stop

@section('breadcrumbs')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">@lang('app.home')</a></li>
        <li class="breadcrumb-item"><a href="{{ route('admin.announcement.index') }}">@lang('app.announcement')</a></li>
        <li class="breadcrumb-item active" aria-current="page">@lang('global.app_edit')</li>
    </ol>
@endsection


@section('content')
<div class="row mB-40">

	<div class="col-sm-12">
        <div class="card p-30 bd">
            <h6><a class="float-left" href="{{ route('admin.announcement.index') }}"><i class="ti-arrow-left mR-10"></i></a></h6>
            <hr class="mB-30">
            
            {!! Form::model($announcement, [
                    'route' => ['admin.announcement.update', $announcement->id],
					'method' => 'put', 
					'files' => true
				])
			!!}
                
                <div class="form-group row mt-3">
                    <label class="col-sm-2 col-form-label text-right">@lang('app.title') <span class="text-danger">*</span></label>
                    <div class="col-sm-8">
                        {!! Form::text('title', old('title'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                        <p class="help-block"></p>
                        @if($errors->has('title'))
                            <p class="help-block">
                                {{ $errors->first('title') }}
                            </p>
                        @endif
                    </div>
                </div>  

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label text-right">@lang('app.content')</label>
                    <div class="col-sm-6">
                        {!! Form::textarea('content', old('content'), ['class' => 'form-control description', 'rows' => 4, 'placeholder' => '']) !!}
                        <p class="help-block"></p>
                        @if($errors->has('content'))
                            <p class="help-block">
                                {{ $errors->first('content') }}
                            </p>
                        @endif
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label text-right">@lang('app.expired')</label>
                    <div class="col-sm-4">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="ti-calendar"></i></span>
                            </div>
                            {!! Form::text('expired', date('d/m/Y',strtotime( $announcement->expired))  , ['class' => 'form-control  datepicker', 'placeholder' => '', 'required' => '']) !!}
                        </div>
                        <p class="help-block"></p>
                        @if($errors->has('expired'))
                            <p class="help-block">
                                {{ $errors->first('expired') }}
                            </p>
                        @endif
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label text-right">@lang('app.status') <span class="text-danger">*</span></label>
                    <div class="col-sm-6">
                        <input type="checkbox" name="status" class="switch switch-info" id="status" value="{{ $announcement->status or '0'}}">
                        <p class="help-block"></p>
                        @if($errors->has('status'))
                            <p class="help-block">
                                {{ $errors->first('status') }}
                            </p>
                        @endif
                    </div>
                </div>
                
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label text-right"></label>
                    <div class="col-sm-8">
                        <a href="{{ route('admin.announcement.index') }}" class="btn btn-light">{{ trans('global.app_cancel') }}</a>
                        {!! Form::submit(trans('global.app_save'), ['class' => 'btn btn-danger']) !!}
                    </div>
                </div>
				
			{!! Form::close() !!}
		</div>  
	</div>
</div>
	
@stop

@section('js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/5.0.11/tinymce.min.js"></script>
    <script>
        $(document).ready(function() {
            if($('#status').val()=='1'){
                $('#status').attr('checked','checked').iCheck('update');
            }
            $('#status').on('ifChecked', function(){
                $("#status" ).attr('value', '1');
            });
            $('#status').on('ifUnchecked', function(){
                $("#status" ).attr('value', '0');
            });
            tinymce.init({
                selector:'textarea.description',
                width: 800,
                height: 300
            });
        });
    </script>
@stop

resources/views/admin/announcement/index.blade.php
@extends('layouts.app')

@section('page-header')
    @lang('app.announcement')
@endsection

@section('breadcrumbs')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">@lang('app.home')</a></li>
        <li class="breadcrumb-item active" aria-current="page">@lang('app.announcement')</li>
    </ol>
@endsection

@section('content')

<div class="row mB-40">
    <div class="col-sm-12">
        <div class="card p-20 bd">
            <div class="m-b-20">
                <a href="{{ route('admin.announcement.create') }}" class="btn btn-info btn-sm">
                    {{ trans('global.app_create') }}
                </a>
            </div>
            <div class="table-responsive">
                <table id="dataTables" class="table table-striped table-bordered" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>{{ __('app.title') }}</th>
                            <th>{{ __('app.status') }}</th>
                            <th>{{ __('app.updated') }}</th>
                            <th>{{ __('app.action') }}</th>
                        </tr>
                    </thead>
                
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

@section('js')
    <script>
    $(document).ready(function() {
        $('#dataTables').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{{ route('admin.announcement.datatables') }}',
            columns: [
                {data: 'title', name: 'title'},
                {data: 'status', name: 'status',  orderable: false, searchable: false},
                {data: 'updated_at', name: 'updated_at', searchable: false},
                {data: 'action', name: 'action', orderable: false, searchable: false}
            ]
        });
    });
</script>
@stop