routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});


Route::get('locale/{locale}', function ($locale) {
    Session::put('locale', $locale);
    return redirect()->back();
});

Route::get('assesment-input', ['uses' => 'Performance\AssessmentController@input','as' => 'assesment.input']);

Route::get('performance/get_assessment/{type?}/{year?}', ['uses' => 'ApiPerformanceController@get_assessment','as' => 'performance.get']);


Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware'=>['auth']], function () {
    Route::get('dashboard/{id?}', ['uses' => 'Admin\DashboardController@index', 'as' => 'dashboard'] );
   
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
   
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
   
    Route::resource('users', 'Admin\UsersController')->except(['show']);
    Route::post('users_delete', ['uses' => 'Admin\UsersController@delete', 'as' => 'users.delete']);
    Route::get('users_datatables', ['uses' => 'Admin\UsersController@datatables', 'as' => 'users.datatables'] );
    
    Route::resource('announcement', 'Admin\AnnouncementController');
    Route::post('announcement_delete', ['uses' => 'Admin\AnnouncementController@delete', 'as' => 'announcement.delete']);
    Route::get('announcement_datatables', ['uses' => 'Admin\AnnouncementController@datatables', 'as' => 'announcement.datatables'] );
});

Route::group(['prefix' => 'setting', 'as' => 'setting.', 'middleware'=>['auth']], function () {
    Route::resource('objective_category', 'Setting\ObjectiveCategoryController');
    Route::post('objective_category_delete', ['uses' => 'Setting\ObjectiveCategoryController@delete', 'as' => 'objective_category.delete']);
    Route::get('objective_category_datatables', ['uses' => 'Setting\ObjectiveCategoryController@datatables', 'as' => 'objective_category.datatables'] );
   
    Route::resource('measure', 'Setting\MeasureController');
    Route::post('measure_delete', ['uses' => 'Setting\MeasureController@delete', 'as' => 'measure.delete']);
    Route::get('measure_datatables', ['uses' => 'Setting\MeasureController@datatables', 'as' => 'measure.datatables'] );

    Route::resource('competency', 'Setting\CompetencyController');
    Route::post('competency_delete', ['uses' => 'Setting\CompetencyController@delete', 'as' => 'competency.delete']);
    Route::get('competency_datatables', ['uses' => 'Setting\CompetencyController@datatables', 'as' => 'competency.datatables'] );
   
    Route::resource('group_rater', 'Setting\GroupRaterController');
    Route::post('group_rater_delete', ['uses' => 'Setting\GroupRaterController@delete', 'as' => 'group_rater.delete']);
    Route::get('group_rater_datatables', ['uses' => 'Setting\GroupRaterController@datatables', 'as' => 'group_rater.datatables'] );

    Route::get('rater', ['uses' => 'Setting\RaterController@index', 'as' => 'rater.index'] );
    Route::get('rater_datatables', ['uses' => 'Setting\RaterController@datatables', 'as' => 'rater.datatables'] );
    Route::get('rater/{id}', ['uses' => 'Setting\RaterController@config', 'as' => 'rater.config'] );
    Route::post('rater_store', ['uses' => 'Setting\RaterController@store', 'as' => 'rater.store']);
    Route::post('rater_destroy', ['uses' => 'Setting\RaterController@destroy', 'as' => 'rater.destroy']);
    Route::get('rater_search', ['uses' => 'Setting\RaterController@search', 'as' => 'rater.search'] );
    
    Route::get('rater_import', ['uses' => 'Setting\RaterController@import', 'as' => 'rater.import'] );
    Route::post('rater_import_store', ['uses' => 'Setting\RaterController@importStore', 'as' => 'rater.importstore']);

    Route::get('general', ['uses' => 'Setting\GeneralController@index', 'as' => 'general.index'] );
    Route::post('general', ['uses' => 'Setting\GeneralController@store', 'as' => 'general.store'] );

    
});

Route::group(['prefix' => 'performance', 'as' => 'performance.', 'middleware'=>['auth']], function () {
   
    Route::get('datatables/{id?}', ['uses' => 'Performance\PerformanceController@datatables', 'as' => 'datatables'] );
    Route::get('data/{id?}', ['uses' => 'Performance\PerformanceController@index','as' => 'data']);
    Route::get('search', ['uses' => 'Performance\PerformanceController@search','as' => 'search']);
    Route::get('export', ['uses' => 'Performance\PerformanceController@export','as' => 'export']);
    Route::get('detail/{id}', ['uses' => 'Performance\PerformanceController@detail','as' => 'detail']);
    Route::get('print/{id}/{score}', ['uses' => 'Performance\PerformanceController@print','as' => 'print']);
    Route::get('show/{type}/{id}', ['uses' => 'Performance\PerformanceController@show','as' => 'show']);
    Route::get('print_kpi/{id}/{type}', ['uses' => 'Performance\MyPerformanceController@printKPI', 'as' => 'print.kpi'] );
    Route::post('destroy', ['uses' => 'Performance\PerformanceController@destroy', 'as' => 'destroy']);
    Route::get('upload', ['uses' => 'Performance\PerformanceController@upload', 'as' => 'upload'] );
    Route::post('upload_store', ['uses' => 'Performance\PerformanceController@uploadStore', 'as' => 'upload.store']);
    Route::get('preview/{id}/{model?}', ['uses' => 'Performance\PerformanceController@preview', 'as' => 'preview'] );
    Route::post('preview_store', ['uses' => 'Performance\PerformanceController@previewStore', 'as' => 'preview.store']);
    Route::post('delete', ['uses' => 'Performance\PerformanceController@delete', 'as' => 'delete']);


    Route::get('history', ['uses' => 'Performance\PerformanceController@history','as' => 'history']);
    Route::get('history_datatables', ['uses' => 'Performance\PerformanceController@historyDatatables', 'as' => 'history.datatables'] );
    Route::get('monitoring/{year?}', ['uses' => 'Performance\PerformanceController@monitoring','as' => 'monitoring']);
    Route::get('monitoring_search', ['uses' => 'Performance\PerformanceController@monitoring_search','as' => 'monitoring.search']);

    Route::get('monitoring_kpi/{year?}/{company?}/{workarea?}/{department?}', ['uses' => 'Performance\PerformanceController@monitoringKPI','as' => 'monitoring.kpi']);
    Route::get('monitoring_kpi_datatables/{year?}/{company?}/{workarea?}/{department?}', ['uses' => 'Performance\PerformanceController@monitoringKPI_datatables','as' => 'monitoring.kpi.datatables']);
    Route::get('monitoring_kpi_search', ['uses' => 'Performance\PerformanceController@monitoringKPI_search','as' => 'monitoring.kpi.search']);

    Route::get('adjust/{id}', ['uses' => 'Performance\PerformanceController@adjust','as' => 'adjust']);
    Route::post('adjust_store', ['uses' => 'Performance\PerformanceController@adjustStore','as' => 'adjust.store']);
    Route::get('adjust_upload', ['uses' => 'Performance\PerformanceController@adjust_upload','as' => 'adjust.upload']);
    Route::post('adjust_upload_store', ['uses' => 'Performance\PerformanceController@adjust_upload_store','as' => 'adjust.upload.store']);


});

Route::group(['middleware'=>['auth']], function () {
    Route::match(['get', 'post'], 'profile/change_profile', ['uses' => 'Admin\ProfileController@changeProfile', 'as' => 'profile.change_profile']);
    Route::match(['get', 'post'], 'profile/change_password', ['uses' => 'Admin\ProfileController@changePassword', 'as' => 'profile.change_password']);
    
    Route::get('announcement_read', ['uses' => 'Admin\AnnouncementController@read', 'as' => 'announcement.read'] );
    Route::post('announcement_read', ['uses' => 'Admin\AnnouncementController@search', 'as' => 'announcement.search'] );
   
    Route::get('notifications', ['uses' => 'Admin\NotificationController@index', 'as' => 'notifications'] );
    Route::get('notifications/{id}', ['uses' => 'Admin\NotificationController@show', 'as' => 'notifications.show'] );
   
    Route::get('get_employee', ['uses' => 'Setting\MasterController@getEmployee'] );
    Route::get('get_department/{id}', ['uses' => 'Setting\MasterController@getDepartment'] );
    Route::get('get_workarea/{id}', ['uses' => 'Setting\MasterController@getWorkarea'] );

});

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Auth::routes();



// EMPLOYEEE
Route::post('signin', ['uses' => 'SigninController@attempt','as' => 'signin']);
Route::post('sign', ['uses' => 'SigninController@login','as' => 'sign']);
Route::get('personal_detail_public/{id}/{year}/', ['uses' => 'Performance\MyPerformanceController@publicView', 'as' => 'personal.public.view'] );
Route::get('personal_detail_print/{id}/{year}/{type}', ['uses' => 'Performance\MyPerformanceController@publicPrint', 'as' => 'personal.public.print'] );

Route::group(['middleware'=>['checksigned']], function () {
    Route::get('announcement_read', ['uses' => 'Dashboard\AnnouncementController@read', 'as' => 'announcement.read'] );
});

Route::group(['prefix' => 'myperformance', 'as' => 'myperformance.', 'middleware'=>['checksigned']], function () {
    
    Route::get('detail/{type}/{id}', ['uses' => 'Performance\MyPerformanceController@detail','as' => 'detail']);
    Route::get('print/{id}/{score}', ['uses' => 'Performance\MyPerformanceController@print', 'as' => 'print'] );
    Route::get('show/{id}', ['uses' => 'Performance\MyPerformanceController@show','as' => 'show']);

app/Http/Controllers/Setting/CompetencyController.php
<?php

namespace App\Http\Controllers\Setting;

use App\Models\Competency;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Vinkla\Hashids\Facades\Hashids;
use Yajra\DataTables\Facades\DataTables;
use Carbon\Carbon;
use Auth;

class CompetencyController extends Controller
{
    /**
     * Display a listing of Group.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('setting')) {
            return abort(401);
        }
        return view('setting.competency.index');
    }

    public function datatables()
    {
        if (! Gate::allows('setting')) {
            return abort(401);
        }
        $result = DB::table('competencies');

       return  DataTables::of($result)
        ->addColumn('action', function ($result) {
            $url_edit = "<a href='".route('setting.competency.edit', Hashids::encode($result->id))."' title='".trans('app.edit_title')."' data-toggle='tooltip' class='btn btn-outline'><span class='ti-pencil icon-lg'></span> </a>";  
            $url_delete = "<form class='delete' action='".route('setting.competency.delete', ['id' => $result->id])."' method='POST'>
                            ".csrf_field()."
                            <button class='btn btn-outline text-danger' title='".trans('app.delete_title')."' data-toggle='tooltip'><i class='ti-trash icon-lg'></i></button>
                          </form>";
            return
                '<div class="btn-group">'
                 .$url_edit .$url_delete.
                '</div>';
        }) 
        ->editColumn('status', function ($result) {
            return getStatusData($result->status);
        })
        ->editColumn('updated_at', function ($result) {
            return $result->updated_at ? with(new Carbon($result->updated_at))->format('m/d/Y') : '';
        })
        ->rawColumns(['action', 'status'])
        ->make(true);

    }

    /**
     * Show the form for creating new Group.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('setting')) {
            return abort(401);
        }

        return view('setting.competency.create');
    }

    /**
     * Store a newly created Group in storage.
     *
     * @param  \App\Http\Requests\StoreGroupsRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (! Gate::allows('setting')) {
            return abort(401);
        }

        $data = $request->all();
        $data['created_by'] = Auth::user()->id;

        $competency = Competency::create($data);

        return redirect()->route('setting.competency.index')->with(['success' => 'Add was successful!']);
    }


    /**
     * Show the form for editing Group.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('setting')) {
            return abort(401);
        }
        $id = Hashids::decode($id);
        $competency = Competency::findOrFail($id['0']);

        return view('setting.competency.edit', compact('competency'));
    }

    /**
     * Update Group in storage.
     *
     * @param  \App\Http\Requests\  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (! Gate::allows('setting')) {
            return abort(401);
        }
        $data = $request->all();
        if($request->get('status')){
            $data['status'] = 1;
        }else{
            $data['status'] = 0;
        }
        $data['updated_by'] = Auth::user()->id;

        $competency = Competency::findOrFail($id);
        $competency->update($data);

        return redirect()->route('setting.competency.index')->with(['success' => 'Edit was successful!']);
        
    }

    /**
     * Remove Group from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {

        print_r($request->id).exit();
        if (! Gate::allows('setting')) {
            return abort(401);
        }

        $competency  = Competency::findOrFail($id);
        $competency->delete();
      
        return redirect()->route('setting.competency.index')->with(['success' => 'Delete was successful!']);

    }

    public function delete(Request $request)
    {

        if (! Gate::allows('setting')) {
            return abort(401);
        }

        $competency  = Competency::findOrFail($request->id);
        $competency->delete();
      
        return redirect()->route('setting.competency.index')->with(['success' => 'Delete was successful!']);

    }

    public function getItem()
    {
        return Competency::get()->pluck('name', 'id');
    }

}

app/Http/Controllers/Setting/GeneralController.php
<?php

namespace App\Http\Controllers\Setting;

use App\Models\Setting;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Vinkla\Hashids\Facades\Hashids;
use Yajra\DataTables\Facades\DataTables;
use Carbon\Carbon;
use Auth;

class GeneralController extends Controller
{
    /**
     * Display a listing of Group.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('setting')) {
            return abort(401);
        }
        return view('setting.general.index');
    }


    /**
     * Update Group in storage.
     *
     * @param  \App\Http\Requests\  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (! Gate::allows('setting')) {
            return abort(401);
        }
        
        $delete = Setting::truncate();

        $setting    = [];
        $key        = $request->get('key');

        for($i=0;$i < count($key);$i++) {
            $setting[] = [
                'key'    => $request->get('key')[$i],
                'value'  => $request->get('val')[$i],
            ];
        }

        $setting = Setting::insert($setting);


        return redirect()->route('setting.general.index')->with(['success' => 'Edit was successful!']);
        
    }


}

app/Http/Controllers/Setting/MasterController.php
<?php

namespace App\Http\Controllers\Setting;

use Illuminate\Http\Request;
use App\Models\Division;
use App\Models\Department;
use App\Models\Employee;
use App\Models\Workarea;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;

class MasterController extends Controller
{
   
    
    public function getEmployee(Request $request)
    {
        if ($request->has('q')) {
            $data = 
            DB::table('db_klola_hes.sys_ttrs_employee AS employee')
            ->select('employee.*', 'department.name AS department','unit.name AS workarea')
            ->where('employee.firstname', 'like', '%' .$request->q . '%')
            ->orWhere('employee.nip', 'like', '%' .$request->q . '%')
            ->leftjoin('db_klola_hes.sys_tmst_department AS department', 'department.id', '=', 'employee.sys_tmst_department_id')
            ->leftjoin('db_klola_hes.sys_tmst_unit AS unit', 'unit.id', '=', 'employee.sys_tmst_unit_id')
            ->get();
            $result = array();    
            foreach ($data as $val) {
                $result[] = array('id' => $val->id,  'nik' => $val->nip, 'name' => $val->firstname, 'department' => $val->department,'workarea' => $val->workarea);
            }
            return response()->json($result);
        }
    }

    public function getDepartment($company)
    {
        return Department::pluck('name', 'id');
    }

    public function getWorkarea($company)
    {
        return Workarea::pluck('name', 'id');
    }


}

resources/views/setting/objective_category/create.blade.php
@extends('layouts.app')

@section('page-header')
    @lang('app.setting')
@endsection

@section('breadcrumbs')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">@lang('app.home')</a></li>
        <li class="breadcrumb-item"><a href="#">@lang('app.setting')</a></li>
        <li class="breadcrumb-item active" aria-current="page">@lang('pm.objective_category')</li>
    </ol>
@endsection

@section('content')

	<div class="row mB-40">
   
        @include('setting.menu')

        <div class="col-sm-9">
            <div class="card p-20 bd">
                
                <h6><a class="float-left" href="{{ route('setting.objective_category.index') }}"><i class="ti-arrow-left m-r-10"></i></a>  @lang('pm.objective_category')</h6>
                <hr class="mB-30">

                {!! Form::open(['method' => 'POST', 'route' => ['setting.objective_category.store']]) !!}
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label text-right"> @lang('app.name') <span class="text-danger">*</span></label>
                        <div class="col-sm-6">
                            {!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                            <p class="help-block"></p>
                            @if($errors->has('name'))
                                <p class="help-block">
                                    {{ $errors->first('name') }}
                                </p>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label text-right"> @lang('app.description') </label>
                        <div class="col-sm-6">
                            {!! Form::textarea('description', old('description'), ['class' => 'form-control', 'rows' => 3, 'placeholder' => '']) !!}
                            <p class="help-block"></p>
                            @if($errors->has('description'))
                                <p class="help-block">
                                    {{ $errors->first('description') }}
                                </p>
                            @endif
                        </div>
                    </div>

                    <hr>
                    <div class="form-group">
                        <div class="ml-auto float-right">
	                        <a href="{{ route('setting.objective_category.index') }}" class="btn btn-light">{{ trans('global.app_cancel') }}</a>
                            <button type="submit" class="btn bg-gradient-success"><i class="ti-save m-r-10"></i> {{ __('app.submit') }}</button>
                        </div>
                    </div>
                    
                {!! Form::close() !!}       
            </div>  
        </div>
    </div>
        
@endsection

resources/views/setting/objective_category/edit.blade.php
@extends('layouts.app')

@section('page-header')
    @lang('app.setting')
@endsection

@section('breadcrumbs')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">@lang('app.home')</a></li>
        <li class="breadcrumb-item"><a href="#">@lang('app.setting')</a></li>
        <li class="breadcrumb-item active" aria-current="page">@lang('pm.objective_category')</li>
    </ol>
@endsection

@section('content')
<div class="row mB-40">

    @include('setting.menu')

	<div class="col-sm-9">
        <div class="card p-30 bd">
            <h6><a class="float-left" href="{{ route('setting.objective_category.index') }}"><i class="ti-arrow-left m-r-10"></i></a> @lang('pm.objective_category')</h6>
            <hr class="mB-30">
            
            {!! Form::model($competency, [
                    'route' => ['setting.objective_category.update', $competency->id],
					'method' => 'put', 
					'files' => true
				])
			!!}
                
                
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label text-right"> @lang('app.name') <span class="text-danger">*</span></label>
                        <div class="col-sm-6">
                            {!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                            <p class="help-block"></p>
                            @if($errors->has('name'))
                                <p class="help-block">
                                    {{ $errors->first('name') }}
                                </p>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label text-right"> @lang('app.description') </label>
                        <div class="col-sm-6">
                            {!! Form::textarea('description', old('description'), ['class' => 'form-control', 'rows' => 3, 'placeholder' => '']) !!}
                            <p class="help-block"></p>
                            @if($errors->has('description'))
                                <p class="help-block">
                                    {{ $errors->first('description') }}
                                </p>
                            @endif
                        </div>
                    </div>

                <div class="form-group row">
                    <label class="col-sm-3 col-form-label text-right"> @lang('app.status')</label>
                    <div class="col-sm-6">
                        <input type="checkbox" name="status" class="switch switch-info" id="status" value="{{ $competency->status or '0'}}">
                        <p class="help-block"></p>
                        @if($errors->has('status'))
                            <p class="help-block">
                                {{ $errors->first('status') }}
                            </p>
                        @endif
                    </div>
                </div>
                
                <hr>
                <div class="form-group">
                    <div class="ml-auto float-right">
                        <a href="{{ route('setting.objective_category.index') }}" class="btn btn-light">{{ trans('global.app_cancel') }}</a>
                        <button type="submit" class="btn bg-gradient-success"><i class="ti-save m-r-10"></i> {{ __('app.submit') }}</button>
                    </div>
                </div>
                    
				
			{!! Form::close() !!}
		</div>  
	</div>
</div>
	
@stop

@section('js')
    <script>
        $(document).ready(function() {
            if($('#status').val()=='1'){
                $('#status').attr('checked','checked').iCheck('update');
            }
            $('#status').on('ifChecked', function(){
                $("#status" ).attr('value', '1');
            });
            $('#status').on('ifUnchecked', function(){
                $("#status" ).attr('value', '0');
            });
        });
    </script>
@stop

resources/views/setting/objective_category/index.blade.php
@extends('layouts.app')

@section('page-header')
    @lang('app.setting')
@endsection

@section('breadcrumbs')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">@lang('app.home')</a></li>
        <li class="breadcrumb-item"><a href="#">@lang('app.setting')</a></li>
        <li class="breadcrumb-item active" aria-current="page">@lang('pm.objective_category')</li>
    </ol>
@endsection

@section('content')

<div class="row mB-40">
 
    @include('setting.menu')

    <div class="col-sm-9">
        <div class="card p-20 bd">
            <h6>
                {{ trans('pm.objective_category') }}
            </h6>
            <hr class="mB-30">
            <div class="mB-20">
                <a href="{{ route('setting.objective_category.create') }}" class="btn btn-info">
                    {{ trans('global.app_create') }}
                </a>
            </div>

            <div class="bd bdrs-3 p-20 mB-20">
                <table id="dataTables" class="table table-striped " cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>{{ trans('app.name') }}</th>
                            <th>{{ trans('app.description') }}</th>
                            <th>{{ trans('app.status') }}</th>
                            <th>{{ trans('app.updated') }}</th>
                            <th>{{ trans('app.action') }}</th>
                        </tr>
                    </thead>
               
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

@section('js')
    <script>
    $(document).ready(function() {
        $('#dataTables').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{{ route('setting.objective_category.datatables') }}',
            columns: [
                {data: 'name', name: 'name'},
                {data: 'description', name: 'description',  orderable: false, searchable: false},
                {data: 'status', name: 'status',  orderable: false, searchable: false},
                {data: 'updated_at', name: 'updated_at', searchable: false},
                {data: 'action', name: 'action', orderable: false, searchable: false}
            ]
        });
    });
</script>
@stop