routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});


Route::get('locale/{locale}', function ($locale) {
    Session::put('locale', $locale);
    return redirect()->back();
});

Route::get('assesment-input', ['uses' => 'Performance\AssessmentController@input','as' => 'assesment.input']);

Route::get('performance/get_assessment/{type?}/{year?}', ['uses' => 'ApiPerformanceController@get_assessment','as' => 'performance.get']);


Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware'=>['auth']], function () {
    Route::get('dashboard/{id?}', ['uses' => 'Admin\DashboardController@index', 'as' => 'dashboard'] );
   
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
   
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
   
    Route::resource('users', 'Admin\UsersController')->except(['show']);
    Route::post('users_delete', ['uses' => 'Admin\UsersController@delete', 'as' => 'users.delete']);
    Route::get('users_datatables', ['uses' => 'Admin\UsersController@datatables', 'as' => 'users.datatables'] );
    
    Route::resource('announcement', 'Admin\AnnouncementController');
    Route::post('announcement_delete', ['uses' => 'Admin\AnnouncementController@delete', 'as' => 'announcement.delete']);
    Route::get('announcement_datatables', ['uses' => 'Admin\AnnouncementController@datatables', 'as' => 'announcement.datatables'] );
});

Route::group(['prefix' => 'setting', 'as' => 'setting.', 'middleware'=>['auth']], function () {
    Route::resource('objective_category', 'Setting\ObjectiveCategoryController');
    Route::post('objective_category_delete', ['uses' => 'Setting\ObjectiveCategoryController@delete', 'as' => 'objective_category.delete']);
    Route::get('objective_category_datatables', ['uses' => 'Setting\ObjectiveCategoryController@datatables', 'as' => 'objective_category.datatables'] );
   
    Route::resource('measure', 'Setting\MeasureController');
    Route::post('measure_delete', ['uses' => 'Setting\MeasureController@delete', 'as' => 'measure.delete']);
    Route::get('measure_datatables', ['uses' => 'Setting\MeasureController@datatables', 'as' => 'measure.datatables'] );

    Route::resource('competency', 'Setting\CompetencyController');
    Route::post('competency_delete', ['uses' => 'Setting\CompetencyController@delete', 'as' => 'competency.delete']);
    Route::get('competency_datatables', ['uses' => 'Setting\CompetencyController@datatables', 'as' => 'competency.datatables'] );
   
    Route::resource('group_rater', 'Setting\GroupRaterController');
    Route::post('group_rater_delete', ['uses' => 'Setting\GroupRaterController@delete', 'as' => 'group_rater.delete']);
    Route::get('group_rater_datatables', ['uses' => 'Setting\GroupRaterController@datatables', 'as' => 'group_rater.datatables'] );

    Route::get('rater', ['uses' => 'Setting\RaterController@index', 'as' => 'rater.index'] );
    Route::get('rater_datatables', ['uses' => 'Setting\RaterController@datatables', 'as' => 'rater.datatables'] );
    Route::get('rater/{id}', ['uses' => 'Setting\RaterController@config', 'as' => 'rater.config'] );
    Route::post('rater_store', ['uses' => 'Setting\RaterController@store', 'as' => 'rater.store']);
    Route::post('rater_destroy', ['uses' => 'Setting\RaterController@destroy', 'as' => 'rater.destroy']);
    Route::get('rater_search', ['uses' => 'Setting\RaterController@search', 'as' => 'rater.search'] );
    
    Route::get('rater_import', ['uses' => 'Setting\RaterController@import', 'as' => 'rater.import'] );
    Route::post('rater_import_store', ['uses' => 'Setting\RaterController@importStore', 'as' => 'rater.importstore']);

    Route::get('general', ['uses' => 'Setting\GeneralController@index', 'as' => 'general.index'] );
    Route::post('general', ['uses' => 'Setting\GeneralController@store', 'as' => 'general.store'] );

    
});

Route::group(['prefix' => 'performance', 'as' => 'performance.', 'middleware'=>['auth']], function () {
   
    Route::get('datatables/{id?}', ['uses' => 'Performance\PerformanceController@datatables', 'as' => 'datatables'] );
    Route::get('data/{id?}', ['uses' => 'Performance\PerformanceController@index','as' => 'data']);
    Route::get('search', ['uses' => 'Performance\PerformanceController@search','as' => 'search']);
    Route::get('export', ['uses' => 'Performance\PerformanceController@export','as' => 'export']);
    Route::get('detail/{id}', ['uses' => 'Performance\PerformanceController@detail','as' => 'detail']);
    Route::get('print/{id}/{score}', ['uses' => 'Performance\PerformanceController@print','as' => 'print']);
    Route::get('show/{type}/{id}', ['uses' => 'Performance\PerformanceController@show','as' => 'show']);
    Route::get('print_kpi/{id}/{type}', ['uses' => 'Performance\MyPerformanceController@printKPI', 'as' => 'print.kpi'] );
    Route::post('destroy', ['uses' => 'Performance\PerformanceController@destroy', 'as' => 'destroy']);
    Route::get('upload', ['uses' => 'Performance\PerformanceController@upload', 'as' => 'upload'] );
    Route::post('upload_store', ['uses' => 'Performance\PerformanceController@uploadStore', 'as' => 'upload.store']);
    Route::get('preview/{id}/{model?}', ['uses' => 'Performance\PerformanceController@preview', 'as' => 'preview'] );
    Route::post('preview_store', ['uses' => 'Performance\PerformanceController@previewStore', 'as' => 'preview.store']);
    Route::post('delete', ['uses' => 'Performance\PerformanceController@delete', 'as' => 'delete']);


    Route::get('history', ['uses' => 'Performance\PerformanceController@history','as' => 'history']);
    Route::get('history_datatables', ['uses' => 'Performance\PerformanceController@historyDatatables', 'as' => 'history.datatables'] );
    Route::get('monitoring/{year?}', ['uses' => 'Performance\PerformanceController@monitoring','as' => 'monitoring']);
    Route::get('monitoring_search', ['uses' => 'Performance\PerformanceController@monitoring_search','as' => 'monitoring.search']);

    Route::get('monitoring_kpi/{year?}/{company?}/{workarea?}/{department?}', ['uses' => 'Performance\PerformanceController@monitoringKPI','as' => 'monitoring.kpi']);
    Route::get('monitoring_kpi_datatables/{year?}/{company?}/{workarea?}/{department?}', ['uses' => 'Performance\PerformanceController@monitoringKPI_datatables','as' => 'monitoring.kpi.datatables']);
    Route::get('monitoring_kpi_search', ['uses' => 'Performance\PerformanceController@monitoringKPI_search','as' => 'monitoring.kpi.search']);

    Route::get('adjust/{id}', ['uses' => 'Performance\PerformanceController@adjust','as' => 'adjust']);
    Route::post('adjust_store', ['uses' => 'Performance\PerformanceController@adjustStore','as' => 'adjust.store']);
    Route::get('adjust_upload', ['uses' => 'Performance\PerformanceController@adjust_upload','as' => 'adjust.upload']);
    Route::post('adjust_upload_store', ['uses' => 'Performance\PerformanceController@adjust_upload_store','as' => 'adjust.upload.store']);


});

Route::group(['middleware'=>['auth']], function () {
    Route::match(['get', 'post'], 'profile/change_profile', ['uses' => 'Admin\ProfileController@changeProfile', 'as' => 'profile.change_profile']);
    Route::match(['get', 'post'], 'profile/change_password', ['uses' => 'Admin\ProfileController@changePassword', 'as' => 'profile.change_password']);
    
    Route::get('announcement_read', ['uses' => 'Admin\AnnouncementController@read', 'as' => 'announcement.read'] );
    Route::post('announcement_read', ['uses' => 'Admin\AnnouncementController@search', 'as' => 'announcement.search'] );
   
    Route::get('notifications', ['uses' => 'Admin\NotificationController@index', 'as' => 'notifications'] );
    Route::get('notifications/{id}', ['uses' => 'Admin\NotificationController@show', 'as' => 'notifications.show'] );
   
    Route::get('get_employee', ['uses' => 'Setting\MasterController@getEmployee'] );
    Route::get('get_department/{id}', ['uses' => 'Setting\MasterController@getDepartment'] );
    Route::get('get_workarea/{id}', ['uses' => 'Setting\MasterController@getWorkarea'] );

});

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Auth::routes();



// EMPLOYEEE
Route::post('signin', ['uses' => 'SigninController@attempt','as' => 'signin']);
Route::post('sign', ['uses' => 'SigninController@login','as' => 'sign']);
Route::get('personal_detail_public/{id}/{year}/', ['uses' => 'Performance\MyPerformanceController@publicView', 'as' => 'personal.public.view'] );
Route::get('personal_detail_print/{id}/{year}/{type}', ['uses' => 'Performance\MyPerformanceController@publicPrint', 'as' => 'personal.public.print'] );

Route::group(['middleware'=>['checksigned']], function () {
    Route::get('announcement_read', ['uses' => 'Dashboard\AnnouncementController@read', 'as' => 'announcement.read'] );
});

Route::group(['prefix' => 'myperformance', 'as' => 'myperformance.', 'middleware'=>['checksigned']], function () {
    
    Route::get('detail/{type}/{id}', ['uses' => 'Performance\MyPerformanceController@detail','as' => 'detail']);
    Route::get('print/{id}/{score}', ['uses' => 'Performance\MyPerformanceController@print', 'as' => 'print'] );
    Route::get('show/{id}', ['uses' => 'Performance\MyPerformanceController@show','as' => 'show']);

app/Http/Controllers/Performance/AssessmentController.php
<?php

namespace App\Http\Controllers\Performance;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Gate;
use App\Models\Performance;
use App\Models\Division;
use App\Models\Department;
use App\Models\Employee;
use App\Models\Assesment;
use App\Models\Workarea;
use Vinkla\Hashids\Facades\Hashids;
use Yajra\DataTables\Facades\DataTables;

class AssessmentController extends Controller
{   
    
    public function index()
    {
        if (! Gate::allows('performance')) {
            return abort(401);
        }
        $department = DB::table('db_klola_hes.sys_tmst_department')->get()->pluck('name', 'departement_id')->prepend('Silahkan Pilih');
        $workarea   = DB::table('db_klola_hes.sys_tmst_unit')->get()->pluck('name', 'id')->prepend('Silahkan Pilih');
        return view('performance.pm.index',compact('department','workarea'));
    }


    public function input($nik,$id)
    {   
        $nik = Hashids::decode($nik);

        $employee = Employee::where('nik',$nik['0'])->first();
        $assesment = Assesment::where('id',$id['0'])->first();

        return view('performance.pm.assesment',compact ('employee','assesment'));
    }

}

app/Http/Controllers/Performance/MyApprovalController.php
<?php

namespace App\Http\Controllers\Performance;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\DB;
use App\Models\Performance;
use App\Models\PerformanceItem;
use Vinkla\Hashids\Facades\Hashids;
use Yajra\DataTables\Facades\DataTables;
use Carbon\Carbon;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use App\Mail\SendMailable;

class MyApprovalController extends Controller
{   


    public function index()
    {
        $department = DB::table('db_klola_hes.sys_tmst_department')->get()->pluck('name', 'departement_id')->prepend('Silahkan Pilih');
        $workarea   = DB::table('db_klola_hes.sys_tmst_unit')->get()->pluck('name', 'id')->prepend('Silahkan Pilih');
        return view('personal.approval.index',compact('department','workarea'));
    }

    public function datatables()
    {
        $result = Performance::getApprovalList(Session::get('emp_nik'));

        return  DataTables::of($result)
        ->addColumn('action', function ($result) {

            $action = "<a href='".route('myapproval.approve', ['id' => Hashids::encode($result->id)])."' title='".trans('pm.approval')."' data-toggle='tooltip' class='btn btn-warning btn-sm text-white mr-1'> Approve</a>";  
            return $action;

        }) 
        ->addColumn('emp_data', function ($result){
            return "
                <span class='font-weight-bold text-uppercase'>".$result->emp_name."</span><br>
                <span class='text-muted' style='font-size:12px'>
                <i class='ti-card'></i> ".$result->emp_nik." -".$result->emp_workarea." | 
                    ".$result->emp_department."/".$result->emp_occupation."
                 </span>";
        })
            ->rawColumns(['action','action','emp_data','group'])
        ->make(true);

    }


    public function approve($id)
    {   
        $id = Hashids::decode($id);
        $pm = Performance::getPerformanceById($id['0']);
        $pm_items  = Performance::getPerformanceItemById($pm->id,0);
        return view('personal.approval.set',compact ('pm','pm_items'));
       
    }

    public function store(Request $request)
    {   
        
        $pm = Performance::findOrFail($request->get('pm_id'));

        
        $pm_item = $request->get('pm_item');
        $dataPM  = [];


        for($i=0;$i < count($pm_item);$i++) {
            $ids[]      = $request->get('pm_item')[$i];
            $status[]   = "WHEN id = {$request->get('pm_item')[$i]} THEN 1";
            if($request->get('target_revision')[$i] == ""){
                $target[]   = "WHEN id = {$request->get('pm_item')[$i]} THEN NULL";
            }else{
                $target[]   = "WHEN id = {$request->get('pm_item')[$i]} THEN '".$request->get('target_revision')[$i]."'";
            }
        }

        $ids        = implode(',', $ids);
        $status     = implode(' ', $status);
        $target     = implode(' ', $target);

        \DB::update("UPDATE performance_items SET status = CASE {$status} END, target_revision = CASE {$target} END  WHERE id in ({$ids})");

        $data['status'] = 2;
        $pm->update($data);

        return redirect()->route('myapproval.index')->with(['success' => trans('app.message_success_input')]);

    }


}

resources/views/personal/performance/create.blade.php
@extends('layouts.performance')

@section('page-header')
    @lang('pm.my_performance')
@endsection

@section('breadcrumbs')
    <ol class="breadcrumb">
		<li class="breadcrumb-item"><a href="{{ route('myperformance.dashboard') }}">@lang('app.home')</a></li>
        <li class="breadcrumb-item"><a href="{{ route('myperformance.personal.index') }}">@lang('pm.my_performance')</a></li>
        <li class="breadcrumb-item active" aria-current="page">@lang('global.app_create')</li>
    </ol>
@endsection

@section('content')

	<div class="col-lg-12">
	
		<div class="card">
			<div class="card-body p-30">
			
				<h5 class="header-title text-uppercase">
					{{ __('app.form') }} {{ __('pm.performance_appraisal') }}
				</h5>
				<hr>

				<div class="alert alert-info">
					{{ __('pm.form_input_caption') }} 
					<a class="btn btn-danger btn-sm" href="{{ route('myperformance.upload') }}"> @lang('global.upload_data') </a>
				</div>

			    {!! Form::open(['method' => 'POST', 'route' => ['myperformance.personal.store'], 'id'=>'formPM', 'files' => true]) !!}
					
					<div class="form-group row mt-5">
						<label class="col-lg-3 col-form-label">{{ __('pm.periode') }}</label>
						<div class="col-lg-6">
							<div class="input-group">
								<input type="text" name="period_1" class="form-control monthpicker" required>
								<div class="input-group-prepend border-darken-1">
									<span class="input-group-text" >
										<small>s/d</small>
									</span>
								</div>
								<input type="text" name="period_2" class="form-control monthpicker" required>
							</div>
						</div>
					</div>
					<div class="form-group row">
						<label class="col-lg-3 col-form-label">{{ __('pm.year') }}</label>
						<div class="col-lg-2">
							<input type="text" name="year" class="form-control yearpicker" id="yearpicker" required>
						</div>
					</div>
					
					
					<a class="btn btn-success btn-sm text-white add_item float-right mb-2 "><i class="ti-plus"></i> {{ __('global.app_add_new') }} {{ __('pm.kpi') }}</a>
					<table class="table table-bordered table-striped mt-2">
						<thead>
							<th>{{ __('pm.performance_aspect') }}</th>
							<th style="width:200px">{{ __('pm.area_of_performance') }}</th>
							<th style="width:350px">{{ __('pm.kpi') }}</th>
							<th>{{ __('app.weight') }} (%)</th>
							<th style="width:250px">{{ __('pm.target') }} / {{ __('pm.measure') }}</th>
							<th>{{ __('app.action') }}</th>
						</thead>
						<tbody class="item_form">
							<tr> 
								<td> 
									{!! Form::select('pm_aspect[]', $pm_aspect, null, ['class' => 'form-control select2', 'required' => '']) !!}
								</td> 
								<td> 
									<input type="text" name="area[]" class="form-control" required> 
								</td> 
								<td> 
									<input type="text" name="kpi[]" class="form-control" required> 
								</td> 
								<td> 
									<input type="number" name="weight[]" class="form-control weight"  min="0" step="1" required oninput="this.value = Math.abs(this.value)"> 
								</td>
								<td> 
									<input type="text" name="target[]" class="form-control" required> 
									{!! Form::select('measure[]', $measure, null, ['class' => 'form-control select2', 'required' => '']) !!}
								</td> 
								<td> 
								</td> 
							</tr>
						</tbody>
						<tfoot>
								<td colspan="3" class="text-right font-weight-bold text-uppercase">{{ __('pm.total_weight') }} </td>
								<td><span id="totalWeight">0</span> %</td>
								<td colspan="3"></td>
						</tfoot>
					</table>

					<hr>
					<div class="form-group mt-4">
						<div class="ml-auto float-right">
							<a class="btn btn-default" id="btn-cancel" href="{{ route('myperformance.personal.index') }}">{{ __('global.app_cancel') }}</a>
							<input type="hidden" value="0" name="status">
							<button type="submit" name="save" class="btn bg-gradient-blue" id="btn-draft"><i class="m-r-10"></i> {{ __('global.app_save_draft') }}</button>
							<button type="submit" class="btn bg-gradient-success" id="btn-submit"><i class="ti-save m-r-10"></i> {{ __('global.app_submit') }}</button>
						</div>
					</div>

				</form>
				
			</div>
		</div>
			
	</div>

@endsection

@section('js')
	<script>
		$(document).ready(function(){
			
			var wrapper = $(".item_form");
			var add_sk = $(".add_item");
			var i = 0;
			var m = 0;
			$(document).on("click", ".add_item", function(e) {
				e.preventDefault();
				i++;


				var id = "#row_" + i;
				$(wrapper).append(
					'<tr>' +
						'<td>' +
							'<select name="pm_aspect[]" class="form-control select2" id="pm_aspect_'+i+'" required></select>' +
						'</td>' +
						'<td>' +
							'<input type="text" name="area[]" class="form-control" required>' +
						'</td>' +
						'<td>' +
							'<input type="text" name="kpi[]" class="form-control" required>' +
						'</td>' +
						'<td>' +
							'<input type="number" name="weight[]" class="form-control weight"  id="weight_'+i+'"  min="0" step="1" oninput="this.value = Math.abs(this.value)" required>' +
						'</td>'+
						'<td>' +
							'<input type="text" name="target[]" class="form-control" required>' +
							'<select name="measure[]" class="form-control select2" id="measure_'+i+'" required></select>' +
						'</td>' +
						'<td>' +
							'<a href="#" class="remove_item btn btn-danger btn-md pull-right"><i class="ti-trash"></i></a>' +
                            '<div id="js_'+i+'" ></div>'+
						'</td>' +
					'</tr>'
				);

				$.getJSON("/myperformance/get_objective_category/" , function(data){
					$.each(data, function(value, key) {
						$('#pm_aspect_'+i).append($("<option></option>").attr("value", value).text(key)); // name refers to the objects value when you do you ->lists('name', 'id') in laravel
					});
				});

				$.getJSON("/myperformance/get_measure/" , function(data){
					$.each(data, function(value, key) {
						$('#measure_'+i).append($("<option></option>").attr("value", value).text(key)); // name refers to the objects value when you do you ->lists('name', 'id') in laravel
					});
				});
				
				$('#pm_aspect_'+i).select2();
				$('#measure_'+i).select2();
				$(".weight").on("keyup", function() {
					calculateSum($(this).attr("id"));
				});
				m++;
			});

			$(document).on("click", ".remove_item", function() {
				$(this).parents("tr").remove();
			});

			$(document).on("click", "#btn-submit", function(e) {
				$('input[name="status"]').val('1');
			});
			
		
		});

		

		function calculateSum(id){
			var sum = 0;
			var sumt = 0;
			$(".weight").each(function() {
				//add only if the value is number
				if (!isNaN(this.value) && this.value.length != 0) {
					sum += parseFloat(this.value);
					$(this).css("background-color", "#FEFFB0");
					if(sum > 100){
						Swal.fire(
							'{{ __("app.notice") }}!',
							'{{__("pm.message_failed_weight") }}',
							'warning'
						);
						$("#"+id).val('');
					}else{
						sumt += parseFloat(this.value);
					}
				}
				
			});

			$("#totalWeight").text(sumt.toFixed(2));
		}

	</script>
@endsection

resources/views/personal/performance/index.blade.php
@extends('layouts.performance')

@section('page-header')
    @lang('pm.my_performance')
@endsection

@section('breadcrumbs')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('myperformance.dashboard') }}">@lang('app.home')</a></li>
        <li class="breadcrumb-item active" aria-current="page">@lang('pm.my_performance')</li>
    </ol>
@endsection

@section('content')

        <div class="col-lg-12">
                        
            <div class="card">
                <div class="card-body p-30">
                
                    <div class="pad-btm mb-4">
                        <div class="table-toolbar-left">
                            <a class="btn bg-gradient-danger mr-2 btn-sm text-white"  href="{{ route('myperformance.personal.create') }}">{{ __('pm.input_performance') }}</a> 
                           <a class="btn bg-gradient-success mr-2 btn-sm text-white"  href="{{ route('myperformance.upload') }}">{{ __('global.upload_data') }}</a> 
                        </div>
                    </div>  
                    <hr>

                    <div class="table-responsive">
                        <table id="dataTables" class="table table-striped " cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>{{ trans('pm.periode') }}</th>
                                    <th>{{ trans('pm.year') }}</th>
                                    <th>{{ trans('app.status') }}</th>
                                    <th>{{ trans('app.date_input') }}</th>
                                    <th>{{ trans('app.action') }}</th>
                                </tr>
                            </thead>
                            <tbody>
                            
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
                
        </div>

@endsection

@section('js')
    <script>
    $(document).ready(function() {
        $('#dataTables').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{{ route('myperformance.personal.datatables') }}',
            columns: [
                {data: 'period', name: 'period'},
                {data: 'year', name: 'year'},
                {data: 'status', name: 'status', orderable: false, searchable: false},
                {data: 'created_at', name: 'created_at'},
                {data: 'action', name: 'action', orderable: false, searchable: false}
            ]
        });
    });
</script>
@stop

resources/views/personal/performance/upload.blade.php
@extends('layouts.performance')

@section('page-header')
    @lang('pm.my_performance')
@endsection

@section('breadcrumbs')
    <ol class="breadcrumb">
		<li class="breadcrumb-item"><a href="{{ route('myperformance.dashboard') }}">@lang('app.home')</a></li>
        <li class="breadcrumb-item"><a href="{{ route('myperformance.personal.index') }}">@lang('pm.my_performance')</a></li>
        <li class="breadcrumb-item active" aria-current="page">@lang('global.upload_data')</li>
    </ol>
@endsection

@section('content')

   
        <div class="col-sm-12">
            <div class="card p-20 bd">
                
                <h6> @lang('global.upload_data') </h6>
                <hr class="mB-30">
                <div class="alert alert-info">
                    @lang('pm.form_upload_caption') <a download href="/docs/template-kpi.xlsx" class="btn btn-sm btn-success" title="@lang('global.app_download')" data-toggle='tooltip'><i class="fa fa-file-excel-o"></i> @lang('global.app_download') Template </a> <br>
                </div>
                <form action="{{ route('myperformance.upload.store') }}" method="POST" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <div class="form-group row m-t-30">
						<label class="col-lg-3 col-form-label">{{ __('pm.periode') }}</label>
						<div class="col-lg-4">
							<div class="input-group">
                                {!! Form::text('period_1', old('period_1'), ['class' => 'form-control monthpicker', 'placeholder' => '','id' =>'yearpicker','required' => 'required']) !!}
								<div class="input-group-prepend border-darken-1">
									<span class="input-group-text" >
										<small>s/d</small>
									</span>
								</div>
                                {!! Form::text('period_2', old('period_2'), ['class' => 'form-control monthpicker', 'placeholder' => '','id' =>'yearpicker','required' => 'required']) !!}
							</div>
						</div>
					</div>
                    <div class="form-group row mt-4">
                        <label class="col-sm-3 text-right">@lang('pm.year')</label>
                        <div class="col-sm-2">
                            {!! Form::text('year', old('year'), ['class' => 'form-control yearpicker', 'placeholder' => '','id' =>'yearpicker','required' => 'required']) !!}
                        </div>
                    </div>
                    
                     <div class="form-group row mt-4">
                        <label class="col-sm-3 text-right">@lang('global.file_caption')
                        </label>
                        <div class="col-sm-5">
                            <input type="file" name="file" class="form-control">
                        </div>
                    </div>
                    <hr>
                    <div class="form-group">
                        <div class="ml-auto float-right">
	                        <a href="{{ route('performance.data') }}" class="btn btn-light">{{ trans('global.app_cancel') }}</a>
                            <button type="submit" class="btn bg-gradient-success"><i class="ti-save m-r-10"></i> {{ __('app.submit') }}</button>
                        </div>
                    </div>

                {!! Form::close() !!}       
            </div>  
        </div>
        
@endsection


@section('js')
	<script>
		$(document).ready(function(){

			
		});
	</script>
@endsection